{
 "title": "Debug",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All storages capacity",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "max(vm_rpc_max_capacity)", "legendFormat": "__auto" },
    { "expr": "max(vm_rpc_used_capacity)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Capacity per storage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(vm_rpc_max_capacity) by (instance)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Avg RPM",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    { "expr": "vm_rpc_avg_rps", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Storage Avg Dur",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    { "expr": "vm_rpc_avg_dur", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "backpreassure",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "max(vm_rows_inserted_backpressure_capacity_limit)",
     "legendFormat": "max"
    },
    {
     "expr": "max(vm_rows_inserted_backpressure_capacity_used)",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "in total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(vm_rows_inserted_ok_total[$__rate_interval]))",
     "legendFormat": "ok"
    },
    {
     "expr": "sum(rate(vm_rows_inserted_denied_total[$__rate_interval]))",
     "legendFormat": "denied"
    },
    {
     "expr": "sum(rate(vm_rows_inserted_congested_total[$__rate_interval]))",
     "legendFormat": "congested"
    }
   ]
  }
 ]
}