services:
  vmagent:
    image: victoriametrics/vmagent:v1.115.0
    depends_on:
      - "vmauth"
    ports:
      - 8429:8429
    volumes:
      - vmagentdata:/vmagentdata
      - ./provisioning/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--promscrape.config=/etc/prometheus/prometheus.yml"
      - "--remoteWrite.url=http://vminsert:8480/insert/0/prometheus/api/v1/write"
    restart: always

  # Grafana instance configured with VictoriaMetrics as datasource
  grafana:
    container_name: grafana
    image: grafana/grafana:11.5.0
    depends_on:
      - "vmauth"
    ports:
      - 3000:3000
    restart: always
    volumes:
      - grafanadata:/var/lib/grafana
      - ./provisioning/datasources/prometheus-datasource/cluster.yml:/etc/grafana/provisioning/datasources/cluster.yml
      - ./provisioning/datasources/victoriametrics-logs-datasource/single.yml:/etc/grafana/provisioning/datasources/vlogs.yml
      - ./provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./provisioning/query-stats.json:/var/lib/grafana/dashboards/query-stats.json
    environment:
      - "GF_INSTALL_PLUGINS=victoriametrics-logs-datasource"

  vmstorage-1:
    container_name: vmstorage-1
    image: victoriametrics/vmstorage:v1.113.0-cluster
    ports:
      - 8482
      - 8400
      - 8401
    volumes:
      - strgdata-1:/storage
    command:
      - "--storageDataPath=/storage"
    restart: always
  vmstorage-2:
    container_name: vmstorage-2
    image: victoriametrics/vmstorage:v1.113.0-cluster
    ports:
      - 8482
      - 8400
      - 8401
    volumes:
      - strgdata-2:/storage
    command:
      - "--storageDataPath=/storage"
    restart: always

  vminsert:
    container_name: vminsert
    image: victoriametrics/vminsert:v1.113.0-cluster
    depends_on:
      - "vmstorage-1"
      - "vmstorage-2"
    command:
      - "--storageNode=vmstorage-1:8400"
      - "--storageNode=vmstorage-2:8400"
    ports:
      - 8480:8480
    restart: always

  vmselect-1:
    container_name: vmselect-1
    image: victoriametrics/vmselect:heads-query-stats-cluster-0-gcec879def4-dirty-ab5fef54
    depends_on:
      - "vmstorage-1"
      - "vmstorage-2"
    command:
      - "--storageNode=vmstorage-1:8401"
      - "--storageNode=vmstorage-2:8401"
      - "--vmalert.proxyURL=http://vmalert:8880"
      - "--search.logSlowQueryStats=1us"
      - "--eula"
    ports:
      - 8481
    restart: always
  vmselect-2:
    container_name: vmselect-2
    image: victoriametrics/vmselect:heads-query-stats-cluster-0-gcec879def4-dirty-ab5fef54
    depends_on:
      - "vmstorage-1"
      - "vmstorage-2"
    command:
      - "--storageNode=vmstorage-1:8401"
      - "--storageNode=vmstorage-2:8401"
      - "--vmalert.proxyURL=http://vmalert:8880"
      - "--search.logSlowQueryStats=1us"
      - "--eula"
    ports:
      - 8481
    restart: always

  vmauth:
    container_name: vmauth
    image: victoriametrics/vmauth:v1.113.0
    depends_on:
      - "vmselect-1"
      - "vmselect-2"
    volumes:
      - ./provisioning/auth.yml:/etc/auth.yml
    command:
      - "--auth.config=/etc/auth.yml"
    ports:
      - 8427:8427
    restart: always

  vmalert:
    container_name: vmalert
    image: victoriametrics/vmalert:v1.113.0
    depends_on:
      - "vmauth"
    ports:
      - 8880:8880
    volumes:
      - ./provisioning/alerts.yml:/etc/alerts/alerts.yml
    command:
      - "--datasource.url=http://vmauth:8427/select/0/prometheus"
      - "--remoteRead.url=http://vmauth:8427/select/0/prometheus"
      - "--remoteWrite.url=http://vminsert:8480/insert/0/prometheus"
      - "-notifier.blackhole"
      - "--rule=/etc/alerts/*.yml"
      # display source of alerts in grafana
      - "-external.url=http://127.0.0.1:3000" #grafana outside container
      - '--external.alert.source=explore?orgId=1&left={"datasource":"VictoriaMetrics","queries":[{"expr":{{.Expr|jsonEscape|queryEscape}},"refId":"A"}],"range":{"from":"{{ .ActiveAt.UnixMilli }}","to":"now"}}'
    restart: always

  victorialogs:
    container_name: victorialogs
    image: victoriametrics/victoria-logs:v1.17.0-victorialogs
    command:
      - "--storageDataPath=/vlogs"
      - "--httpListenAddr=:9428"
    volumes:
      - vldata:/vlogs
    ports:
      - "9428:9428"

  vector:
    image: docker.io/timberio/vector:0.42.X-distroless-libc
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /var/lib/docker
        target: /var/lib/docker
      - ./provisioning/vector.yml:/etc/vector/vector.yaml:ro
    depends_on: [victorialogs]
    ports:
      - "8686:8686"
    user: root

volumes:
  vmagentdata: {}
  vldata: {}
  strgdata-1: {}
  strgdata-2: {}
  grafanadata: {}