apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: demo
  namespace: vm
spec:
  # Metrics source (VMStorage/VMCluster/VMSingle)
  datasource:
    url: "http://vmsingle-demo.vm.svc:8429"

  # Where to send alert state
  remoteWrite:
    url: "http://vmsingle-demo.vm.svc:8429"

  # Where to load previous alert state from
  remoteRead:
    url: "http://vmsingle-demo.vm.svc:8429"

  # Alertmanager URL for sending alerts
  notifier:
    url: "http://vmalertmanager-demo.vm.svc:9093"

  # How often to evaluate rules
  evaluationInterval: "30s"

  # Watch VMRule resources in all namespaces
  selectAllByDefault: true
