apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlertmanager
metadata:
  name: demo
  namespace: vm
spec:
  configRawYaml: |
    #    global:
    #      resolve_timeout: 5m
    route:
      #      group_wait: 30s
      #      group_interval: 5m
      #      repeat_interval: 12h
      receiver: 'webhook'
    receivers:
    - name: 'webhook'
      webhook_configs:
      - url: 'http://demo-app.default.svc:8080/alerting/webhook'
