apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: disable-mtls-for-victoriametrics-webhook
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: victoria-metrics-operator
  mtls:
    mode: DISABLE