apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: demo
  namespace: vm
spec:
  podMetadata:
    annotations:
      proxy.istio.io/config: |
        proxyMetadata:
          OUTPUT_CERTS: /etc/istio-certs
      sidecar.istio.io/userVolumeMount: '[{"name": "istio-certs", "mountPath": "/etc/istio-certs"}]'
      traffic.sidecar.istio.io/includeInboundPorts: ""
      traffic.sidecar.istio.io/includeOutboundIPRanges: ""
  remoteWrite:
  - url: http://vmsingle-demo.vm.svc:8429/api/v1/write
  selectAllByDefault: true
  volumeMounts:
  - mountPath: /etc/istio-certs/
    name: istio-certs
    readOnly: true
  volumes:
  - emptyDir:
      medium: Memory
    name: istio-certs
